In [1]:
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC

diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
lasso = linear_model.Lasso()


In [2]:
# Single metric evaluation using cross_validate

cv_results = cross_validate(lasso, X, y, cv=3)
sorted(cv_results.keys())
cv_results['test_score']


array([0.33150734, 0.08022311, 0.03531764])

In [3]:
scores = cross_validate(lasso, X, y, cv=3,
                         scoring=('r2', 'neg_mean_squared_error'),
                        return_train_score=True)

print(scores['test_neg_mean_squared_error'])
print(scores['train_r2'])


[-3635.51152303 -3573.34242148 -6114.78229547]
[0.28010158 0.39088426 0.22784852]


In [11]:
import numpy as np
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()
loo.get_n_splits(X)

for train_index, test_index in loo.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    scores = cross_validate(lasso, X_train, y_train, cv=3,
                         scoring=('r2', 'neg_mean_squared_error'),
                        return_train_score=True)
    print(scores['test_neg_mean_squared_error'])
#     print(cv_results['test_score'])
    

[-3608.18419219 -3655.00096702 -6278.27497573]
[-3583.82623936 -3682.0418189  -6305.07759769]
[-3607.99096323 -3657.74025509 -6269.98227392]
[-3568.35126375 -3626.7130079  -6337.77854698]
[-3619.0063476  -3649.59185742 -6271.3966794 ]
[-3599.93425577 -3674.98639399 -6280.70196637]
[-3612.84428335 -3632.3825632  -6255.40497537]
[-3497.95789496 -3690.20300547 -6228.65908637]
[-3560.30311424 -3657.44084787 -6200.40275214]
[-3294.74870958 -3616.37956312 -6709.56687413]
[-3617.37768316 -3656.35463283 -6288.77349038]
[-3550.79858414 -3669.03916308 -6249.12887141]
[-3579.96937432 -3620.84670328 -6277.10734173]
[-3609.35206882 -3646.37470686 -6323.85582198]
[-3613.39314009 -3663.13744525 -6271.6965591 ]
[-3615.55096562 -3651.63142794 -6296.30413078]
[-3615.6490897  -3659.16645243 -6294.62630266]
[-3611.5911878  -3665.51792128 -6266.75334442]
[-3575.64547418 -3680.34512159 -6250.34963394]
[-3607.67651233 -3638.92831026 -6292.30481018]
[-3533.8716011  -3717.11547188 -6301.89794824]
[-3505.669952